### ISSUE TITLE
CMS BootStrap Blog update and tweaks

### ISSUE THREAD

**Issue by bitniko** [MicheleDeF/CMS-BootStrap-Blog#1]
hello, you have a nice work..
i have some questions:
recently i started to use your CMS Bootstrap blog, do you plan to update it to Bootstrap v3.3.7?
there is no problem using Bootstrap v2.3.2?
is it worth update it?
is it possible to remove javascript like cookie policy, whats the instructions?
is it possible to make the CMS more lighweight and fast by removing unused code?
do you have a template that looks exactly like this [version](https://getbootstrap.com/examples/blog/)?

ps. how do i add RSS feeds?
thanks..

**Comment by MicheleDeF** [comment]
You can make any changes, but you have to do it.

**Comment by MicheleDeF** [comment]
If you can give me the link of the site where you used my CMS.

**Comment by bitniko** [comment]
MicheleDeF,
here you have php/mysql code to add RSS feed using your CMS..
[pastebin](https://pastebin.com/89GC6hJ8)

Regards..
